"""create ables

Revision ID: ff6fabdb4062
Revises: 
Create Date: 2020-05-06 09:40:04.827390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6fabdb4062'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=80), nullable=True),
    sa.Column('channel', sa.String(length=80), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('nature', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_channel'), 'channel', ['channel'], unique=False)
    op.create_index(op.f('ix_channel_timestamp'), 'channel', ['timestamp'], unique=False)
    op.create_index(op.f('ix_channel_userid'), 'channel', ['userid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_userid'), table_name='channel')
    op.drop_index(op.f('ix_channel_timestamp'), table_name='channel')
    op.drop_index(op.f('ix_channel_channel'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
